sudo: false
language: c
compiler: gcc
env:
  global:
    - NAME=luci-app-clash
  matrix:
  - SDK_URL=https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64.tar.xz

install:
- wget -c $SDK_URL
- cd $TRAVIS_BUILD_DIR
- export FILE=$TRAVIS_BUILD_DIR/$(basename $SDK_URL)
- file $FILE
- tar xvJf $FILE

script:
- wget -q https://raw.githubusercontent.com/frainzy1477/luci-app-clash/New-LuciMaster-Lean/config -O 2>&1 >1 $TRAVIS_BUILD_DIR/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/.config
- cd $TRAVIS_BUILD_DIR/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/package/
- git clone -b koolshare-lede-openwrt https://github.com/frainzy1477/luci-app-clash.git 
- cd $TRAVIS_BUILD_DIR/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64
- make package/luci-app-clash/compile V=99

before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: "dGhWwj/+4k+P6ZYsyzNez7lQxF+luUMn9E8oafm5ouR/HXCbEOJV3IGINBNviqwxA6cLxaIh9kdfuK6iSQjT/u7Mc5PDAFWaZ+ITegxU9mJzC71kiZ+WxS69czAjELOI6762VZbB5eq3igv9AIXD6X1dE7u2E6eM9DIw36aiXsfTZsesK/lAfzgfpShD/hY+eASt6A7XWDtZL1tTWaUimNAqnwkvmuGYsjyh1lYhe/se5vR7nLQR9f/FykZugif2do7q326Zkfd5K7+Dy8Wz+r1ZmzxrgDPxM3w0nKs3kFvMqWMnrEVbzDKgKuVCuBPGPAoBePRp51ytoRBQXH+obfxqHaK2LZVJQ6LSQwgcvxP/zFn37r/IKzR0Uor+dH//NNAJey4v2fYjD+Fzw/JTam2objLLyroR+AewWQ07y0VkqQr4UNsXUE3kvhoCXaEv5QOGtsV4mjBBkTO6CcfZzn3rZKzqwKdznHXRMgucE5B6+eTz06dXF6Z5x2EF5uPV2nHKazrSicDvNX1dvdF99jfj/4MolxBSu1Y59cfX9hUUmedpeOvp3NQ7MWrvicDZLK0qp3uVsOUjQkskYu+YzCs8+MjFKEi8ikYeGcxJdOoFEX51VH3UAwfOXfUhTF5HymGqed5qxPnXAdzrxJbj5LJYc4YFVwSMukT+QOHpGNA="
  skip_cleanup: true
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/bin/packages/x86_64/base/*.ipk"
  on:
    tags: true
    repo: frainzy1477/luci-app-clash
    all_branches: true
